### ISSUE TITLE
Unexpected behavior for invariant checking

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/smart#6]
This example fails, but I was expecting it to go through.

```scala
import stainless.annotation._
import stainless.smartcontracts._
import Environment._

trait A extends Contract {
  @addressOfContract("A")
  var a: Address
  var x: BigInt

  final def constructor(_a: Address) = {
    a = _a
    dynAssert(contractAt(a).asInstanceOf[A].x >= 0)
  }

  final def invariant() = {
    contractAt(a).asInstanceOf[A].x >= 0
  }
}
```

**Comment by Frostweeds** [comment]
Due to the annotation `@addressOfContract("A")`, you have to add to more assumption on `a` in the constructor : `contractAt(a).isInstanceOf[A] && contractAt(a).isInstanceOf[A].addr == a`. However, apparently this still fails, but it works if you do

```
dynAssert(contractAt(_a).isInstanceOf[A])
dynAssert(contractAt(_a).asInstanceOf[A].addr == _a)
dynAssert(contractAt(_a).asInstanceOf[A].x >= 0)
a = _a
```
Do you know why ?

**Comment by jad-hamza** [comment]
Thanks that makes sense. There seems to be a bug (maybe from the way Stainless generates VCs) where the last `dynAssert` is not taken into account.

**Comment by jad-hamza** [comment]
The bug was reported in https://github.com/epfl-lara/stainless/issues/531 and fixed in https://github.com/epfl-lara/inox/pull/99.
